# Generated by Django 2.2.4 on 2023-08-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0003_auto_20230807_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Guest',
        ),
    ]
