# Generated by Django 2.2.4 on 2023-08-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
