# Generated by Django 2.2.4 on 2023-08-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0006_staff_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password_confirmation',
            field=models.CharField(default='DEFAULT VALUE', max_length=225),
        ),
    ]
