# Generated by Django 2.2.4 on 2023-08-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0007_staff_password_confirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
