# Generated by Django 2.2.4 on 2023-08-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0013_auto_20230810_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='password_confirmation',
        ),
    ]
