# Generated by Django 2.2.4 on 2023-08-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0015_auto_20230813_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='reason',
            field=models.CharField(max_length=225),
        ),
    ]
