# Generated by Django 2.2.4 on 2023-08-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0016_auto_20230813_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='guest',
            name='client',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
