# Generated by Django 2.2.4 on 2023-08-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0018_auto_20230814_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='first_name',
            new_name='provider_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
    ]
