# Generated by Django 2.2.4 on 2023-08-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0024_guest_signed_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='signed_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
