# Generated by Django 2.2.4 on 2023-08-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCC_app', '0025_auto_20230817_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='signed_in',
        ),
    ]
